#!/usr/bin/env bash

#: exec_target = cli

## Install a fresh Drupal site
##
## Usage: fin drush-site-install

# Abort if anything fails
set -e

#-------------------------- Settings --------------------------------

# PROJECT_ROOT and DOCROOT are set as env variables in cli
DOCROOT_PATH="${PROJECT_ROOT}/${DOCROOT}"

#-------------------------- END: Settings --------------------------------

#-------------------------- Helper functions --------------------------------

# Console colors
red='\033[0;31m'
green='\033[0;32m'
green_bg='\033[1;97;42m'
yellow='\033[1;33m'
NC='\033[0m'

echo-red () { echo -e "${red}$1${NC}"; }
echo-green () { echo -e "${green}$1${NC}"; }
echo-green-bg () { echo -e "${green_bg}$1${NC}"; }
echo-yellow () { echo -e "${yellow}$1${NC}"; }

#-------------------------- END: Helper functions ---------------------------

#-------------------------- Functions --------------------------------

# Install site
site_install ()
{
	cd "$DOCROOT_PATH"

	echo-green "Installing Drupal..."
	drush site-install standard -y --site-name='My Drupal 9 Site'
}

#-------------------------- END: Functions --------------------------------

#-------------------------- Execution --------------------------------

# Drupal site initialization
time -p site_install

#-------------------------- END: Execution --------------------------------
